#!/usr/bin/env bash

scriptDir="$(dirname "$0")"
cd $scriptDir

function installPackages {
    sudo apt update
    sudo apt -y dist-upgrade
    sudo apt -y autoremove

    packages=(
        # Base
        'ssh'
        'git'
        'fish'
        'curl'
        'nmap'
        'unzip'
        'nano'
        'net-tools'
        'zfsutils-linux'
        'traceroute'
        'sshfs'
        'ntpdate'
        'htop'
        # Desktop Environment
        'xinit'
        'bspwm'
        'feh'
        'arandr'
        'caffeine'
        'redshift'
        'dmenu'
        'xbindkeys'
        'nautilus'
        # Desktop
        'lxappearance'
        'chromium-browser'
        'firefox'
        'tilix'
        # Themeing
        'arc-theme'
        'dmz-cursor-theme'
        # bspwm - complile
        'gcc'
        'make'
        'xcb'
        'libxcb-util0-dev'
        'libxcb-ewmh-dev'
        'libxcb-randr0-dev'
        'libxcb-icccm4-dev'
        'libxcb-keysyms1-dev'
        'libxcb-xinerama0-dev'
        'libasound2-dev'
        'libxcb-xtest0-dev'
    )

    for package in ${packages[@]} ; do
        sudo apt install -y $package
    done

}

function installBspwm {
    cd
    git clone https://github.com/baskerville/bspwm.git
    cd bspwm

    git pull

    make
    sudo make install

}

function installConfigFiles {
    cd $scriptDir

    mkdir -p ~/.config/bspwm 2> /dev/null

    touch ~/.Xauthority

    ln -sf config/bspwmrc ~/.config/bspwm/bspwmrc
    ln -sf config/xinitrc ~/.xinitrc
    ln -sf config/xresources ~/.xresources
    ln -sf config/xbindkeysrc ~/.xbindkeysrc
    pwd
    crontab < config/crontab
}


installPackages
installBspwm
installConfigFiles
