#!/usr/bin/env bash

# merge X resources
xrdb -merge $HOME/.xresources

# Set default cursor
xsetroot -cursor_name left_ptr &

# use saved screenlayout script from arandr
screenLayoutScript=$HOME/.screenlayout/main.sh
if [ -f "$screenLayoutScript" ] ; then
    $screenLayoutScript &
fi

# Start bspwm
exec caffeinate bspwm
